@startuml
autonumber

IjkMediaPlayer [#FF0000]-> ijkplayer_jni:setDataSourceAndHeaders()

ijkplayer_jni [#FF0000]-> ijkplayer:ijkmp_set_data_source()

ijkplayer [#000000]-> ijkplayer:ijkmp_set_data_source_l()

ijkplayer [#000000]-> ijkplayer:ijkmp_change_state_l(MP_STATE_INITIALIZED)

ijkplayer [#FF0000]-> ff_ffplay_def:ffp_notify_msg1(FFP_MSG_PLAYBACK_STATE_CHANGED)

ff_ffplay_def [#FF0000]-> ff_ffmsg_queue:msg_queue_put_simple3()

ff_ffmsg_queue [#000000]-> ff_ffmsg_queue:msg_queue_put()

ff_ffmsg_queue [#000000]-> ff_ffmsg_queue:msg_queue_put_private()



@enduml