@startuml
autonumber


ffplay -> ffplay: audio_open()

group audio_open
    ffplay [#red]-> channel_layout: av_get_default_channel_layout()

    ffplay [#red]-> channel_layout: av_get_channel_layout_nb_channels()

    ffplay [#blue]-> SDL: SDL_OpenAudioDevice(sdl_audio_callback)

    SDL -> ffplay:sdl_audio_callback()

    ffplay -> ffplay:audio_decode_frame()

    group sdl_audio_callback

        ffplay -> samplefm:av_samples_get_buffer_size()

        ffplay -> ffplay:synchronize_audio()

        ffplay -> swresample:swr_init()

        ffplay -> swresample:swr_convert()
    end
end



@enduml