@startuml
autonumber
hide footbox
title 权益信息普通流程时序图

Client -> SDK: init()
activate SDK
SDK [#FFB383]-> UserPowerImpl:  加载文件缓存
SDK [#FFB383]-> UserPowerImpl:  获取服务端数据
UserPowerImpl [#FFB383]-> UserPowerImpl: 使用文件缓存初始化内存缓存
UserPowerImpl -> VipServer: 请求服务端数据
UserPowerImpl <--[#0000FF] VipServer: 返回全量权益数据
UserPowerImpl [#FFB383]-> UserPowerImpl : 使用网络数据初始化内存缓存，缓存新数据到SP中
UserPowerImpl -> SDK: 分发数据改变通知
SDK -> Client: 分发数据改变通知

||45||

Client -> SDK: 根据ID查询缓存中的权益状态
SDK -> UserPowerImpl: 在缓存中查询权益状态
UserPowerImpl -> SDK: 返回权益状态(PowerQueryResult)
SDK -> Client: 返回权益状态(PowerQueryResult)

||45||

Client -> SDK: 根据ID查询最新权益状态
SDK -> UserPowerImpl: 请求网络获取最新的权益数据
UserPowerImpl -> UserPowerImpl : 判断是否处于防分享状态
UserPowerImpl -> SDK: 若处于防分享，返回异常数据
UserPowerImpl -> UserPowerImpl: 若不处于防分享，根据ID查询权益状态
UserPowerImpl -> SDK: 返回权益状态(PowerQueryResult)
SDK -> Client: 返回权益状态(PowerQueryResult)

newpage


Passport -> SDK: 用户退出
SDK [#FFB383]-> SDK: 清除内存数据
SDK -> Client: 分发权益变化通知

newpage


Passport -> SDK: 用户登录
SDK [#FFB383]-> UserPowerImpl: 清除缓存数据
UserPowerImpl -> VipServer: 请求服务端数据
UserPowerImpl <--[#0000FF] VipServer: 返回全量数据
UserPowerImpl [#FFB383]-> UserPowerImpl: 更新数据到内存中


@enduml