@startuml

interface IUserInfoListener {
    void onSuccess(UserInfo vipUserInfo);
    void onFailure(ApiResponse response);
}

class UserInfo
class UserMemberInfo
class UserGradeInfo
class UserAutoInfo

UserInfo o-- UserMemberInfo : aggregation
UserInfo o-- UserGradeInfo : aggregation
UserInfo o-- UserAutoInfo : aggregation

class VipUserService {
    UserInfo getUserInfo();
    void getUserInfoNewest(IUserInfoListener listener);
}

VipUserService *-- UserInfoImpl

@enduml