#ifndef SPLAYER_MAC_DEFINE_H
#define SPLAYER_MAC_DEFINE_H

#define VERSION_MODULE_FILE_NAME_LENGTH  13
#define VIDEO_PICTURE_QUEUE_SIZE  3
#define SUBPICTURE_QUEUE_SIZE  16
#define SAMPLE_QUEUE_SIZE  9
#define FRAME_QUEUE_SIZE FFMAX(SAMPLE_QUEUE_SIZE, FFMAX(VIDEO_PICTURE_QUEUE_SIZE, SUBPICTURE_QUEUE_SIZE))

#endif //SPLAYER_MAC_DEFINE_H
