
#ifndef SPLAYER_CORE_ERRORNO_H
#define SPLAYER_CORE_ERRORNO_H

#define SERROR 0
#define SE_NULL 2
#define SE_NXIO  4
#define SE_CONDITION  5
#define SE_NOT_MEMORY  6
#define SE_NOT_OPEN_INPUT 7
#define SE_NOT_FIND_PARAMETERS 8
#define SE_NOT_OPEN_FILE 9


#endif //SPLAYER_CORE_ERRORNO_H
