/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.1.1-26-g1e50a327c64"
#endif /* AVUTIL_FFVERSION_H */
