@startuml
autonumber


ijkplayer_jni -> ijkplayer_jni:mediacodec_select_callback()

ijkplayer_jni -> ijksdl_android_jni:SDL_JNI_SetupThreadEnv()

ijksdl_android_jni -> IjkMediaPlayer.c:J4AC_IjkMediaPlayer__onSelectCodec__withCString__asCBuffer()

IjkMediaPlayer.c -> IjkMediaPlayer.c:J4AC_tv_danmaku_ijk_media_player_IjkMediaPlayer__onSelectCodec__withCString()

IjkMediaPlayer.c -> IjkMediaPlayer.c:J4AC_tv_danmaku_ijk_media_player_IjkMediaPlayer__onSelectCodec()

IjkMediaPlayer.c -> IjkMediaPlayer.java:onSelectCodec()

IjkMediaPlayer.java -> DefaultMediaCodecSelector.java:onMediaCodecSelect()

ijkplayer_jni -> j4a_base:J4A_ExceptionCheck__catchAll()

@enduml