#ifndef SPLAYER_ANDROID_SLESAUDIODEVICE_H
#define SPLAYER_ANDROID_SLESAUDIODEVICE_H

#include <device/AudioDevice.h>

class SLESAudioDevice : AudioDevice {

};


#endif //SPLAYER_ANDROID_EXAMPLE_SLESAUDIODEVICE_H
