@startuml
autonumber

IjkMediaPlayer.java [#FF0000]-> ijkplayer_jni:prepareAsync()

ijkplayer_jni [#FF0000]-> ijkplayer:ijkmp_prepare_async()

ijkplayer [#000000]-> ijkplayer:ijkmp_prepare_async_l()

ijkplayer [#000000]-> ijkplayer:ijkmp_change_state_l(MP_STATE_ASYNC_PREPARING)

ijkplayer [#FF0000]-> ff_ffmsg_queue:msg_queue_start(FFP_REQ_PAUSE)

ijkplayer [#FF0000]-> ijksdl_thread:SDL_CreateThreadEx()

ijksdl_thread [#FF0000]-> ijkplayer:ijkmp_msg_loop()

ijkplayer [#FF0000]-> ijkplayer_jni:msg_loop()

ijkplayer [#FF0000]-> ff_ffplay:ffp_prepare_async_l()

ff_ffplay [#FF0000]-> ff_ffpipeline:ffpipeline_open_audio_output()

ff_ffplay [#000000]-> ff_ffplay:stream_open()

ff_ffplay [#FF0000]-> ijksoundtouch_wrap:ijk_soundtouch_create()

ff_ffplay [#000000]-> ff_ffplay:frame_queue_init()

ff_ffplay [#000000]-> ff_ffplay:packet_queue_init()

ff_ffplay [#000000]-> ff_ffplay:video_refresh_thread()

ff_ffplay [#000000]-> ff_ffplay:read_thread()



@enduml