@startuml
autonumber
loop

ff_ffplay -> options:avformat_alloc_context()

ff_ffplay -> format:av_find_input_format()

ff_ffplay -> utils:avformat_open_input()

ff_ffplay -> ff_ffmsg:ffp_notify_msg1(FFP_MSG_OPEN_INPUT)

ff_ffplay -> dump:av_dump_format()

ff_ffplay -> utils:av_find_best_stream()

ff_ffplay -> ff_ffplay:stream_component_open(AUDIO)

ff_ffplay -> ff_ffplay:stream_component_open(VIDEO)

ff_ffplay -> ff_ffplay:stream_component_open(SUBTITLE)

ff_ffplay -> ff_ffmsg:ffp_notify_msg1(FFP_MSG_COMPONENT_OPEN)

ff_ffplay -> ff_ffmsg:ffp_notify_msg3(FFP_MSG_VIDEO_SIZE_CHANGED)

ff_ffplay -> ff_ffmsg:ffp_notify_msg3(FFP_MSG_SAR_CHANGED)

ff_ffplay -> ff_ffmsg:ffp_notify_msg1(FFP_MSG_PREPARED)

ff_ffplay -> ff_ffmsg:ffp_notify_msg1(FFP_REQ_START)



end
@enduml