@startuml
autonumber

ijkplayer_android -> ffpipeline_android:ffpipeline_create_from_android()

ffpipeline_android -> ffpipeline_android:func_destroy()

ffpipeline_android -> ffpipeline_android:func_open_video_decoder()

group func_open_video_decoder

    alt mediacodec
        ffpipeline_android -> ffpipeline_android:ffpipenode_create_video_decoder_from_android_mediacodec()
    else
        ffpipeline_android -> ffpipenode_ffplay_vdec:ffpipenode_create_video_decoder_from_ffplay()

        ffpipenode_ffplay_vdec -> ffpipenode_ffplay_vdec:func_run_sync()

        group func_run_sync

            ffpipenode_ffplay_vdec -> ff_ffplay:ffp_video_thread()

            ffpipenode_ffplay_vdec -> ff_ffplay:ffplay_video_thread()

        end

        ffpipenode_ffplay_vdec -> ffpipenode_ffplay_vdec:func_destroy()
    end

end

ffpipeline_android -> ffpipeline_android:func_open_audio_output()

group func_open_audio_output

    alt opensles

        ffpipeline_android -> ijksdl_aout_android_opensled:SDL_AoutAndroid_CreateForOpenSLES()

    else

        ffpipeline_android -> ijksdl_aout_android_audiotrack:SDL_AoutAndroid_CreateForAudioTrack()

    end

    ffpipeline_android -> ijksdl_aout:SDL_AoutSetStereoVolume()

end

ffpipeline_android -> ffpipeline_android:func_init_video_decoder()

ffpipeline_android -> ffpipenode_android_mediacodec_vdec:ffpipenode_init_decoder_from_android_mediacodec()

ffpipeline_android -> ffpipeline_android:func_config_video_decoder()

@enduml