@startuml
autonumber

IjkMediaPlayer -> ijkplayer_jni:pause()

ijkplayer_jni -> ijkplayer:ijkmp_pause()

ijkplayer -> ijkplayer:ijkmp_pause_l()

ijkplayer -> ijkplayer:ffp_remove_msg(FFP_REQ_START)

ijkplayer -> ijkplayer:ffp_remove_msg(FFP_REQ_PAUSE)

ijkplayer -> ijkplayer:ffp_notify_msg1(FFP_REQ_PAUSE)

@enduml