@startuml
autonumber

IjkMediaPlayer -> ijkplayer_jni:stop()

ijkplayer_jni -> ijkplayer:ijkmp_stop()

ijkplayer -> ijkplayer:ijkmp_stop_l()

ijkplayer -> ijkplayer:ffp_remove_msg(FFP_REQ_START)

ijkplayer -> ijkplayer:ffp_remove_msg(FFP_REQ_PAUSE)

ijkplayer -> ff_ffplay:ffp_stop_l()

group ffp_stop_l

ff_ffplay -> ff_ffplay:toggle_pause()

ff_ffplay -> ff_ffplay:toggle_pause_l()

ff_ffplay -> ff_ffplay:stream_update_pause_l()

ff_ffplay -> ff_ffplay:stream_toggle_pause_l()

ff_ffplay -> ijksdl_aout:SDL_AoutPauseAudio()

ff_ffplay -> ff_ffmsg_queue:msg_queue_abort()

end

ijkplayer -> ijkplayer:ijkmp_change_state_l(MP_STATE_STOPPED)

ijkplayer -> ijkplayer:ffp_notify_msg1(MP_STATE_STOPPED)


@enduml