@startuml
autonumber

IjkMediaPlayer -> IjkMediaPlayer:unLoadLibrary()

System -> ijkplayer_jni:JNI_OnUnload()

ijkplayer_jni -> ijkplayer:ijkmp_global_uninit()

ijkplayer -> ff_ffplay:ffp_global_uninit()

ff_ffplay [#red]-> utils:av_lockmgr_register()

ff_ffplay [#red]-> utils:avformat_network_deinit()

@enduml