@startuml
autonumber

IjkMediaPlayer [#000000]-> IjkMediaPlayer:initPlayer

IjkMediaPlayer [#000000]-> IjkMediaPlayer:loadLibrariesOnce()

IjkMediaPlayer [#FF0000]-> System:loadLibrary("ijksdl")

System [#FF0000]-> ijksdl_android_jni:JNI_OnLoad()

ijksdl_android_jni [#FF0000]-> j4a_allclasses:J4A_LoadAll__catchAll()

@enduml