@startuml
autonumber

ffplay -> ffplay: read_thread()

ffplay [#red]-> options:avformat_alloc_context()

ffplay [#red]-> utils:avformat_open_input()

ffplay [#red]-> dump:av_dump_format()

ffplay [#red]-> utils:av_find_best_stream()

ffplay [#red]-> utils:av_guess_sample_aspect_ratio()

ffplay -> ffplay:set_default_window_size()

ffplay -> fflay:stream_component_open()

    group stream_component_open

    ffplay [#red]-> options:avcodec_alloc_context3()

    ffplay [#red]-> utils:avcodec_parameters_to_context()

    ffplay [#red]-> allcodecs:avcodec_find_decoder()

    ffplay [#red]-> utils:avcodec_open2()

        alt audio

            ffplay -> ffplay: audio_open()

            ffplay -> ffplay: decoder_init()

            ffplay -> ffplay: decoder_start(audio_thread)

            loop audio_thread

                ffplay -> ffplay:decoder_decode_frame()

                ffplay -> ffplay:frame_queue_peek_writable()

                ffplay[#red]-> frame:av_frame_move_ref()

                ffplay -> ffplay:frame_queue_push()

            end

        else video

            ffplay -> ffplay: decoder_init()

            ffplay -> ffplay: decoder_start(video_thread)

            ffplay [#red]-> frame:av_frame_alloc()

            loop video_thread

                ffplay -> ffplay:get_video_frame()

                ffplay -> ffplay:decoder_decode_frame()

                    group decoder_decode_frame
                        ffplay [#red]-> decodec:avcodec_send_packet()

                        ffplay [#red]-> avpacket:av_packet_move_ref()

                        ffplay [#red]-> decodec:avcodec_receive_frame()

                    end

                ffplay [#red]-> utils:av_guess_sample_aspect_ratio()

                ffplay -> ffplay:queue_picture()

                    group queue_picture

                    ffplay -> ffplay:frame_queue_peek_writable()

                    ffplay -> ffplay:set_default_window_size()

                    ffplay [#red]-> frame:av_frame_move_ref()

                    ffplay -> ffplay:frame_queue_push()
                    end

            end

        else subtitle

            ffplay -> ffplay: decoder_init()

            ffplay -> ffplay: decoder_start(subtitle_thread)

            loop subtitle_thread

                ffplay -> ffplay:frame_queue_peek_writable()

                ffplay -> ffplay:decoder_decode_frame()

                ffplay -> ffplay:frame_queue_push()

            end

        end

    end

    loop

        ffplay -> fflay:abort

        ffplay -> fflay:pause

        ffplay -> fflay:seek

        ffplay -> fflay:buffer

        ffplay -> utils:av_read_frame()

        ffplay -> ffplay:packet_queue_put(packet)

    end

@enduml