#ifndef ERRORS_H
#define ERRORS_H

#include <sys/types.h>
#include <cerrno>

enum {
    SUCCESS = 1,
    ERROR_PARAMS = -1,
    ERROR_NOT_MEMORY = -2,
    ERROR_NOT_OPEN_INPUT = -3,
    ERROR_CODEC_OPTIONS = -4,
    ERROR_NOT_FOUND_STREAM_INFO = -5,
    ERROR_DISABLE_ALL_STREAM = -6,
    ERROR_CREATE_DECODER = -7,
    ERROR_NOT_FOUND_DCODE = -8,
    ERROR_NOT_OPEN_DECODE = -9,
    ERROR_EOF = -10,
    ERROR_IO = -11,
    ERROR_STREAM_INDEX = -12,
    ERROR_COPY_CODEC_PARAM_TO_CONTEXT = -13,
};

#endif //ERRORS_H
