/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.1.3-5-g7211e1ca936"
#endif /* AVUTIL_FFVERSION_H */
